config/routes.rb
Atheneum::Application.routes.draw do
  resources :users do
      member do
        get :following, :followers, :borrowing, :borrowers
      end
  end
    
    
  get "sessions/new"
  get "users/new"
  get "pages/home",    :to => 'page#home'
  get "pages/contact", :to => 'page#contact'
  get "pages/about" ,  :to => 'page#about'
  get "pages/help",    :to => 'page#help'

  resources :users
  resources :books, :only => [:create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  resources :borrows, :only => [:create, :destroy]
  
  match '/signup',    :to => 'users#new'
  match '/signin',    :to => 'sessions#new'
  match '/signout',    :to =>'sessions#destroy'
  match '/home',      :to => 'pages#home'
  match '/about',     :to => 'pages#about'
  match '/contact',   :to => 'pages#contact'
  match '/help',      :to => 'pages#help'

   root :to => 'pages#home'

end

app/views/shared/_book_form.html.erb
<%= form_for @book do |f| %>
<%= render 'shared/error_messages2' %>

  <div class="field">
	<%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
<div class="field">
	<%= f.label :authors %><br />
    <%= f.text_area :authors %>
  </div>
<div class="field">
	<%= f.label :isbn %><br />
    <%= f.number_field :isbn %>
  </div>
  <div class="actions">
    <%= f.submit "Add" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages2.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> 
        prohibited this book from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <table class="Books" summary="User books">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="book">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="title"><%= feed_item.title %></span>
    <span class="timestamp">
      By <%= feed_item.authors %> .
    </span>
  </td>
<% if !current_user?(feed_item.user) %>
	<td>
	<% if current_user.borrowing?(feed_item.id) %>
		<%= form_for current_user.borrows.find_by_book_id(feed_item),
             :html => { :method => :delete } do |f| %>
  	<div class="actions"><%= f.submit "Return" %></div>
	<% end %>	
  	<% else %>
   
	<%= form_for current_user.borrows.build(:book_id => feed_item.id) do |f| %>
	<div><%= f.hidden_field :book_id %></div>
	  <div class="actions"><%= f.submit "Borrow" %></div>
	 
	<% end %>
 </td>
	<% end %>
	<% else %>
	   <td>
	      <%= link_to "delete", feed_item, :method => :delete,
	                                       :confirm => "You sure?",
	                                       :title => feed_item.title %>
	    </td>
	  <% end %>
	
</tr>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
	<td>
        <a href="<%= borrowing_user_path(@user) %>">
          <span id="borrowing" class="stat">
            <%= pluralize(@user.borrowing.size, "borrows") %>
          </span>
        </a>
      </td>
	<td>
        <a href="<%= borrowers_user_path(@user) %>">
          <span id="borrowers" class="stat">
            <%= pluralize(@user.numlents, "lends") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="Books">
      <%= pluralize(current_user.books.count, "book") %>
    </span>
  </a>
</div>

app/views/shared/show_borrow.html.erb
<table summary="Information about library borrows/borrowers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Books</strong> <%= @user.books.count %>
      <%= render 'shared/stats' %>
      <% unless @books.empty? %>
        <% @books.each do |book| %>
          <tr>
		  <td class="gravatar">
		    <%= link_to gravatar_for(book.user), book.user %>
		  </td>
		  <td class="book">
		    <span class="user">
		      <%= link_to book.user.name, book.user %>
		    </span>
		    <span class="title"><%= book.title %></span>
		    <span class="timestamp">
		      By <%= book.authors %> .
		    </span>
		  </td>
		</tr>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>